package com.joco.processors;

public enum TagType
{
	TIMESTAMP, DEVICE_DEVICEID, DEVICE_SESSIONID, 
	GPS_LAT, GPS_LON, GPS_SPEED, GPS_ALT, GPS_HEADING, GPS_ACCURACY,
	TORQUE_TORQUEID, TORQUE_SESSIONID,
	OBD_SPEED, OBD_RPM, OBD_COOLANT, OBD_TORQUE, OBD_ENGINELOAD, OBD_CO2PRODUCTION, OBD_BATVOLTAGE, OBD_FUELCONSUMPTION,
	PHYS_ACCX, PHYS_ACCY, PHYS_ACCZ, PHYS_TEMP, PHYS_PRESSURE, PHYS_ACCTOTAL
}
